from collections.abc import Callable
from typing import Any

from llm_kee.intent import IntentDetector
from llm_kee.models import (
    EvaluationRecord,
    ImprovementProposal,
    SkillSelectionCycle,
    WorkflowDefinition,
    WorkflowRun,
)
from llm_kee.storage import KEEStore


class SkillSelectionLoop:
    def __init__(
        self,
        store: KEEStore,
        intent_detector: IntentDetector,
        plan_workflow: Callable[[dict[str, Any]], WorkflowDefinition],
        run_workflow: Callable[[WorkflowDefinition], WorkflowRun],
    ) -> None:
        self.store = store
        self.intent_detector = intent_detector
        self.plan_workflow = plan_workflow
        self.run_workflow = run_workflow

    def run(self, task: dict[str, Any]) -> SkillSelectionCycle:
        task_intent = self.intent_detector.detect_task(task)
        workflow = self.plan_workflow(task)
        workflow_run = self.run_workflow(workflow)
        score = 1.0 if workflow_run.status == "completed" else 0.0
        evaluation = EvaluationRecord(
            target_type="workflow_run",
            target_id=workflow_run.id,
            evaluator_name="skill_selection_loop",
            decision="pass" if score >= 0.7 else "review",
            notes=f"Workflow completed with status {workflow_run.status}.",
        )
        evaluation = self.store.evaluation_records.upsert(evaluation)
        improvement_ids: list[str] = []
        if workflow_run.status != "completed" or not workflow.skill_sequence:
            proposal = ImprovementProposal(
                improvement_type="adjust_skill_routing",
                title=f"Adjust skill routing for {task_intent.intent_type}",
                description="Skill loop found a workflow result that needs routing review.",
                intent_ids=[task_intent.id],
                status="pending_review",
                rationale="Generated by Skill Selection Loop.",
            )
            proposal = self.store.improvement_proposals.upsert(proposal)
            improvement_ids.append(proposal.id)
        cycle = SkillSelectionCycle(
            task_intent_id=task_intent.id,
            skill_plan_id=self.store.skill_plans.list()[-1].id if self.store.skill_plans.list() else None,
            workflow_id=workflow.id,
            workflow_run_id=workflow_run.id,
            evaluation_record_ids=[evaluation.id],
            improvement_proposal_ids=improvement_ids,
            status="completed",
        )
        return self.store.skill_selection_cycles.upsert(cycle)
